openapi: 3.0.3
info:
  title: DwarfWeave Author API
  version: 1.0.0
paths:
  /author/suggest:
    post:
      summary: Suggest storylets via LLM
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuggestReq'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuggestResp'
  /author/populate:
    post:
      summary: Bulk populate storylets (AI)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                target_count:
                  type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  added:
                    type: integer
                  total_storylets:
                    type: integer
                  message:
                    type: string
                  auto_improvements:
                    type: string
                  improvement_details:
                    type: object
components:
  schemas:
    SuggestReq:
      type: object
      properties:
        n:
          type: integer
        themes:
          type: array
          items:
            type: string
        bible:
          type: object
    SuggestResp:
      type: object
      properties:
        storylets:
          type: array
          items:
            $ref: '#/components/schemas/StoryletIn'
    StoryletIn:
      type: object
      properties:
        title:
          type: string
        text_template:
          type: string
        requires:
          type: object
        choices:
          type: array
          items:
            type: object
        weight:
          type: number
