openapi: 3.0.3
info:
  title: DwarfWeave Game API
  version: 1.0.0
paths:
  /api/next:
    post:
      summary: Get next storylet for session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NextReq'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NextResp'
  /api/state/{session_id}:
    get:
      summary: Get session state summary
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
  /api/spatial/navigation/{session_id}:
    get:
      summary: Get navigation options
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    NextReq:
      type: object
      properties:
        session_id:
          type: string
        vars:
          type: object
    NextResp:
      type: object
      properties:
        text:
          type: string
        choices:
          type: array
          items:
            $ref: '#/components/schemas/ChoiceOut'
        vars:
          type: object
    ChoiceOut:
      type: object
      properties:
        label:
          type: string
        set:
          type: object
