openapi: 3.0.3
info:
  title: DwarfWeave Spatial API
  version: 1.0.0
paths:
  /api/spatial/navigation/{session_id}:
    get:
      summary: Get 8-directional navigation options
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
  /api/spatial/move/{session_id}:
    post:
      summary: Move player in a specific direction
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                direction:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
  /api/spatial/map:
    get:
      summary: Get spatial map data
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
  /api/spatial/assign-positions:
    post:
      summary: Assign spatial positions to all storylets
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
