openapi: 3.0.3
info:
  title: DwarfWeave State Manager API
  version: 1.0.0
paths:
  /api/state/{session_id}/relationship:
    post:
      summary: Update relationship between entities
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                entity_a:
                  type: string
                entity_b:
                  type: string
                changes:
                  type: object
                memory:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
  /api/state/{session_id}/item:
    post:
      summary: Add item to inventory
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item_id:
                  type: string
                name:
                  type: string
                quantity:
                  type: integer
                properties:
                  type: object
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
  /api/state/{session_id}/environment:
    post:
      summary: Update environmental conditions
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                changes:
                  type: object
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
